spring:
  application:
    name: authorbook
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changemeinprod!
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

